### ISSUE TITLE
re-export num-complex/rustc-serialize

### ISSUE THREAD

**Issue by wcbeard** [rustsim/alga#36]
It would be nice to make the obsoleted rustc-serialize optional by adding it as a default feature that could be turned off. I'm having a hard time compiling to a specific target and it looks like rustc-serialize is the culprit.

Not sure if there's anything in alga that specifically relies on it though.

**Comment by sebcrozet** [comment]
This is no longer a concern as num-complex is no longer compiled with its default features.
