### ISSUE TITLE
Implement traits for i128 and u128

### ISSUE THREAD

**Issue by aplund** [rustsim/alga#81]
The 128bit integers traits do not seem to be implemented.

**Comment by sebcrozet** [comment]
Hi! I agree this would be a great addition, and shouldn't be to difficult to add.

Would you like to make a PR for this? I believe all that needs to be done is to search for all macros currently called for other types of integers [like this](https://github.com/rustsim/alga/blob/dev/alga/src/general/one_operator.rs#L426) and add `i128` and `u128`.

**Comment by sebcrozet** [comment]
Fixed by #82.
